### ISSUE TITLE
GPUassert 35: CUDA driver version is insufficient for CUDA runtime version permutation_search_kernels.cu 378

### ISSUE THREAD

**Issue by InhwanCho** [NVIDIA/apex#1641]
**Describe the Bug**
GPUassert 35: CUDA driver version is insufficient for CUDA runtime version permutation_search_kernels.cu  378

**Minimal Steps/Code to Reproduce the Bug**
```
from apex.contrib.sparsity import ASP
model = ResNet(ResidualBlock, [2, 2, 2]).to(device)

model.load_state_dict(torch.load('./data/res.pth'))
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)
ASP.prune_trained_model(model=model, optimizer=optimizer)
##training code ... ##

##error 
Finding permutation for sibling group 1
[search_for_good_permutation] have merged the weight for node: 'layer1.0.conv1', with its weight shape: 'torch.Size([144, 16])', the matrix_group shape: 'torch.Size([144, 16])'.
[search_for_good_permutation] have merged the weight for node: 'layer1.1.conv1', with its weight shape: 'torch.Size([144, 16])', the matrix_group shape: 'torch.Size([288, 16])'.
[search_for_good_permutation] have merged the weight for node: 'layer2.0.conv1', with its weight shape: 'torch.Size([288, 16])', the matrix_group shape: 'torch.Size([576, 16])'.
[search_for_good_permutation] have merged the weight for node: 'layer2.0.downsample.0', with its weight shape: 'torch.Size([288, 16])', the matrix_group shape: 'torch.Size([864, 16])'.
Searching for a good permutation for this sibling group of shape torch.Size([864, 16])
Found 3 gpus
GPUassert 35: CUDA driver version is insufficient for CUDA runtime version permutation_search_kernels.cu 378
```

I fail to install full-version of Linux apex 
so I install APEX Python-only build via
`pip install -v --disable-pip-version-check --no-cache-dir ./`

I tested sparsity sample test files
but fail to run that code

```
my settings are
ubuntu 20.04 docker 
Driver Version: 515.105.01   CUDA Version: 12.1

torch==1.12.1+cu116 
torchvision==0.13.1+cu116 
torchaudio==0.12.1
```
```[tasklist]
```

**Comment by InhwanCho** [comment]
```
$nvcc --version
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Tue_Feb__7_19:32:13_PST_2023
Cuda compilation tools, release 12.1, V12.1.66
Build cuda_12.1.r12.1/compiler.32415258_0
```

**Comment by InhwanCho** [comment]
I fixed it by rerun the docker image and reinstall stuff

**Comment by cmj18** [comment]
能说一下具体怎么解决的吗
